version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOSTNAME=db
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_INITDB_DATABASE}
    ports:
      - "8080:7331"
    volumes:
      - ./backend/public:/usr/src/app/public
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: node app.js

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:  
      - ./mongodb/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - dbdata:/data/db   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  